version: '3.8'

services:
  sonarqube:
    image: sonarqube:8.9.7-community
    container_name: sonarqube
    ports:
      - "9001:9000"     # SonarQube accessible sur localhost:9001
      - "9093:9092"     # Changement port hôte de 9092 à 9093
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    restart: unless-stopped

  nexus:
    image: sonatype/nexus3
    container_name: nexus
    ports:
      - "8082:8081"     # Nexus accessible sur localhost:8082
    volumes:
      - nexus_data:/nexus-data
    restart: unless-stopped

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  nexus_data:
